services:
  sbt_pars_db:
    container_name: sbt_pars_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    volumes:
      - data_base:/var/lib/postgresql/data
    networks:
      - app-network

  sbt_pars_server:
    container_name: sbt_pars_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - sbt_pars_db
      - redis
    networks:
      - app-network
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    container_name: sbt_pars_redis
    restart: always
    networks:
      - app-network

  celery_worker:
    container_name: sbt_pars_celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A api_server worker -l info --concurrency=1
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
    depends_on:
      - redis
      - sbt_pars_db
      - sbt_pars_server
    networks:
      - app-network
    env_file:
      - .env
    environment:
      API_URL: "http://sbt_pars_server:8000/api/products/import/"
      API_HOST_HEADER: "localhost"
    restart: always

  celery_beat:
    container_name: sbt_pars_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A api_server beat -l info
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
    depends_on:
      - redis
      - sbt_pars_db
      - sbt_pars_server
      - celery_worker
    networks:
      - app-network
    env_file:
      - .env
    environment:
      API_URL: "http://sbt_pars_server:8000/api/products/import/"
      API_HOST_HEADER: "localhost"
    restart: always

networks:
  app-network:
    driver: bridge

  bws_core_network:
    external: true

volumes:
  data_base: