services:
  sbt_pars_db:
    container_name: sbt_pars_db
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    volumes:
      - data_base:/data_base
    networks:
      - app-network

  sbt_pars_server:
    depends_on:
      - sbt_pars_db
    container_name: sbt_pars_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8010:8000'
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    networks:
      - app-network

    env_file:
      - .env
    restart: always
  
  redis:
    image: redis:7
    container_name: sbt_pars_redis
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbt_pars_celery
    command: celery -A api_server worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - sbt_pars_db
    networks:
      - app-network
    env_file:
      - .env


networks:
  app-network:
    driver: bridge
  
  bws_core_network:
    external: true

volumes:
  data_base: