# Generated by Django 5.2.12 on 2026-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='prici_with_iva',
            field=models.BooleanField(default=False),
        ),
    ]
