# Generated by Django 5.2.12 on 2026-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsupplier_prici_with_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupplier',
            name='prici_with_iva',
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='price_with_iva',
            field=models.BooleanField(default=False),
        ),
    ]
