# Generated by Django 5.2.12 on 2026-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsupplier_prici_with_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_sbt',
            field=models.IntegerField(null=True),
        ),
    ]
