# Generated by Django 5.2.12 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_code_sbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_sbt',
            field=models.IntegerField(null=True, verbose_name='Код СБТ'),
        ),
    ]
