# Generated by Django 5.2.12 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_code_sbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_sbt',
            field=models.CharField(max_length=255, verbose_name='Название СБТ'),
        ),
    ]
