# Generated by Django 5.2.12 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_title_sbt'),
        ('supplier', '0008_alter_supplier_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductSupplier', to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
