# Generated by Django 5.2.12 on 2026-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_suppliers'),
        ('supplier', '0016_alter_supplier_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductSupplier', to='supplier.supplier'),
        ),
    ]
