# Generated by Django 5.2.12 on 2026-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_category_alter_product_suppliers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sbt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена СБТ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_sbt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код СБТ'),
        ),
    ]
