# Generated by Django 5.2.12 on 2026-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_title_sbt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='price_wholesale_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена'),
        ),
    ]
