# Generated by Django 5.2.12 on 2026-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productsupplier_price_wholesale_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsupplier',
            options={'ordering': ['price_wholesale_final'], 'verbose_name': 'Цена поставщика', 'verbose_name_plural': 'Цены поставщиков'},
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена из прайса'),
        ),
    ]
