# Generated by Django 5.2.12 on 2026-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productsupplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая ориг. цена из прайса'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='price_wholesale_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена скидки и IVA'),
        ),
    ]
