# Generated by Django 5.2.12 on 2026-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productsupplier_price_wholesale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupplier',
            name='iva_in_price',
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='price_wholesale_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая финальная цена'),
        ),
    ]
