# Generated by Django 5.2.12 on 2026-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productsupplier_iva_in_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
