# Generated by Django 5.2.12 on 2026-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productsupplier_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
