# Generated by Django 5.2.12 on 2026-04-22 17:08

import django.db.models.deletion
import mercado_libre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_alter_productsupplier_price_wholesale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('ml_page', models.URLField(blank=True, null=True, verbose_name='Ссылка Mercado Libre')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('price_list', models.FileField(blank=True, null=True, storage=mercado_libre.models.OverwriteStorage(), upload_to=mercado_libre.models.mercadolibre_price_upload_path, verbose_name='Прайс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Магазин Mercado Libre',
                'verbose_name_plural': 'Магазины Mercado Libre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MercadoLibreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_prod_code', models.CharField(max_length=255, verbose_name='Код товара магазина')),
                ('shop_prod_title', models.CharField(max_length=255, verbose_name='Название товара магазина')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена из прайса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadolibre_products', to='product.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadolibre_products', to='mercado_libre.mercadolibreshop', verbose_name='Магазин Mercado Libre')),
            ],
            options={
                'verbose_name': 'Товар Mercado Libre',
                'verbose_name_plural': 'Товары Mercado Libre',
                'ordering': ['price'],
                'unique_together': {('product', 'shop')},
            },
        ),
    ]
