# Generated by Django 5.2.12 on 2026-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='price_list',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
