# Generated by Django 5.2.12 on 2026-03-28 15:41

import supplier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_list',
            field=models.FileField(blank=True, null=True, upload_to=supplier.models.supplier_price_upload_path),
        ),
    ]
