# Generated by Django 5.2.12 on 2026-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_facebook_alter_supplier_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='login',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
