# Generated by Django 5.2.12 on 2026-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_login_supplier_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
