# Generated by Django 5.2.12 on 2026-03-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_supplier_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='updated',
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
