# Generated by Django 5.2.12 on 2026-04-09 15:38

import supplier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_remove_supplier_updated_supplier_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_list',
            field=models.FileField(blank=True, null=True, storage=supplier.models.OverwriteStorage(), upload_to=supplier.models.supplier_price_upload_path),
        ),
    ]
