# Generated by Django 5.2.12 on 2026-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_supplier_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
