# Generated by Django 5.2.12 on 2026-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_alter_supplier_facebook_alter_supplier_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
    ]
