# Generated by Django 5.2.12 on 2026-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0014_alter_supplier_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='login',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Логин'),
        ),
    ]
