# Generated by Django 5.2.12 on 2026-04-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0015_alter_supplier_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль'),
        ),
    ]
