# Generated by Django 5.2.12 on 2026-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0016_alter_supplier_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplier',
            name='upt_price_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновление прайса'),
        ),
    ]
