# Generated by Django 5.2.12 on 2026-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0017_remove_supplier_updated_at_supplier_upt_price_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Скидка %'),
        ),
    ]
