# Generated by Django 5.2.12 on 2026-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0018_supplier_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка %'),
        ),
    ]
