# Generated by Django 5.2.12 on 2026-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0019_alter_supplier_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='iva_in_price',
            field=models.BooleanField(default=False),
        ),
    ]
