# Generated by Django 5.2.12 on 2026-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0020_supplier_iva_in_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='iva_in_price',
            field=models.BooleanField(default=False, verbose_name='IVA'),
        ),
    ]
