# Generated by Django 5.2.12 on 2026-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0021_alter_supplier_iva_in_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ib_caba_in_prise',
            field=models.BooleanField(default=False, verbose_name='IB CABA'),
        ),
    ]
