# Generated by Django 5.2.12 on 2026-04-23 15:18

import supplier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0022_supplier_ib_caba_in_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USA Dollar'), ('ARS', 'ARS Peso')], default='ARS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ib_caba_in_prise',
            field=models.BooleanField(default=False, verbose_name='IB CABA включен в цену'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='iva_in_price',
            field=models.BooleanField(default=False, verbose_name='IVA включен в цену'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price_list',
            field=models.FileField(blank=True, null=True, storage=supplier.models.OverwriteStorage(), upload_to=supplier.models.supplier_price_upload_path, verbose_name='Прайс'),
        ),
    ]
