# Generated by Django 5.2.12 on 2026-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0023_supplier_currency_alter_supplier_ib_caba_in_prise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USA'), ('ARS', 'ARS')], default='ARS', max_length=3, verbose_name='Валюта'),
        ),
    ]
