# Generated by Django 5.2.12 on 2026-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0024_alter_supplier_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='ARS', max_length=3, verbose_name='Валюта'),
        ),
    ]
