# Generated by Django 5.2.12 on 2026-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0025_alter_supplier_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='data_type',
            field=models.CharField(blank=True, choices=[('doc', 'doc'), ('web', 'web')], null=True, verbose_name='Тип данных'),
        ),
    ]
