# Generated by Django 5.2.12 on 2026-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0026_supplier_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='data_type',
            field=models.CharField(blank=True, choices=[('doc', 'doc'), ('web', 'web'), ('doc, web', 'Doc Web')], null=True, verbose_name='Тип данных'),
        ),
    ]
