# Generated by Django 5.2.12 on 2026-04-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_parsers_app', '0002_alter_parserjob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserjob',
            name='name',
            field=models.CharField(choices=[('duna', 'Duna'), ('electrocity', 'Electrocity'), ('electrofrig', 'Electrofrig'), ('fijamom', 'Fijamom'), ('nordfrig', 'Nordfrig'), ('roma', 'Roma'), ('ansal', 'Ansal'), ('reld_retail', 'Reld retail')], max_length=100, unique=True, verbose_name='Код парсера'),
        ),
    ]
