# Generated by Django 5.2.12 on 2026-04-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_parsers_app', '0005_alter_parserjob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserjob',
            name='name',
            field=models.CharField(choices=[('duna', 'Duna'), ('electrocity', 'Electrocity'), ('electrofrig', 'Electrofrig'), ('fijamom', 'Fijamom'), ('nordfrig', 'Nordfrig'), ('roma', 'Roma'), ('ansal', 'Ansal'), ('ansal_retail', 'Ansal retail'), ('reld_retail', 'Reld retail'), ('bellini_retail', 'Bellini retail'), ('refrigeracion_norte_retail', 'Refrigeracion Norte retail')], max_length=100, unique=True, verbose_name='Код парсера'),
        ),
    ]
