# Generated by Django 5.2.12 on 2026-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_parsers_app', '0006_alter_parserjob_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserjob',
            options={'ordering': ['name'], 'verbose_name': 'Парсер', 'verbose_name_plural': 'Парсеры'},
        ),
        migrations.RemoveField(
            model_name='parserjob',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='parserjob',
            name='title',
        ),
        migrations.AlterField(
            model_name='parserjob',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='parserjob',
            name='last_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parserjob',
            name='name',
            field=models.CharField(choices=[('duna', 'Duna'), ('electrocity', 'Electrocity'), ('electrofrig', 'Electrofrig'), ('fijamom', 'Fijamom'), ('nordfrig', 'Nordfrig'), ('roma', 'Roma'), ('ansal', 'Ansal'), ('ansal_retail', 'Ansal retail'), ('reld_retail', 'Reld retail'), ('bellini_retail', 'Bellini retail'), ('refrigeracion_norte_retail', 'Refrigeracion Norte retail')], max_length=100, unique=True, verbose_name='Парсер'),
        ),
    ]
