version: "3.9"

services:
  nordfrig_parser:
    build: .
    container_name: nordfrig_parser

    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data

    environment:
      - LOG_FILE=/app/logs/nordfrig.log
      - API_URL=http://host.docker.internal:8010/api/products/import/

    extra_hosts:
      - "host.docker.internal:host-gateway"
